<a href="https://colab.research.google.com/github/ArtisticWenny/datasci_3_eda/blob/main/cleaned_dataset_for_Hospital_Cost_Report_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Google Drive

In [9]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

Load in packages and Load in data

In [10]:
import pandas as pd

csv_file_path = ['/content/drive/MyDrive/Hospital_Cost_Report_2019.csv']

df = pd.read_csv('/content/drive/MyDrive/Hospital_Cost_Report_2019.csv')

print(df.head)

<bound method NDFrame.head of       rpt_rec_num  Provider CCN                         Hospital Name  \
0          700569         52043   1125 SIR FRANCIS DRAKE OPERATING CO
1          698041        421301         ABBEVILLE AREA MEDICAL CENTER
2          709145        190034            ABBEVILLE GENERAL HOSPITAL
3          705454        240057          ABBOTT NORTHWESTERN HOSPITAL
4          705220        450558                   ABILENE REG MED CTR
...           ...           ...                                   ...
6113       713551         61315                YUMA DISTRICT HOSPITAL
6114       707159         30013          YUMA REGIONAL MEDICAL CENTER
6115       685609         33034  YUMA REHABILITATION HOSPITAL  AN AFF
6116       687770        192041        ZACHARY-AMG SPECIALTY HOSPITAL
6117       708981         50228      ZUCKERBERG SAN FRANCISCO GENERAL

                     Street Address           City State Code    Zip Code  \
0       1125 SIR FRANCIS DRAKE BLVD      KENTFIELD         CA  94904-1455
1     ABBEVILLE AREA MEDICAL CENTER      ABBEVILLE         SC       29620
2          118 NORTH HOSPITAL DRIVE      ABBEVILLE         LA  70511-0580
3              800 EAST 28TH STREET    MINNEAPOLIS         MN       55407
4                    6250 HWY 83/84        ABILENE         TX       79606
...                             ...            ...        ...         ...
6113           1000 WEST 8TH AVENUE           YUMA         CO      80759-
6114                2400 S AVENUE A           YUMA         AZ       85364
6115           901 WEST 24TH STREET           YUMA         AZ       85364
6116        4601 MCHUGH RD.  BLDG B        ZACHARY         LA       70791
6117            1001 POTRERO AVENUE  SAN FRANCISCO         CA      94110-

                     County  Medicare CBSA Number Rural Versus Urban  ...  \
0                       NaN               94904.0                  U  ...
1                 ABBEVILLE               99942.0                  R  ...
2                 VERMILION               29180.0                  R  ...
3                  HENNEPIN               33460.0                  U  ...
4                    TAYLOR               10180.0                  U  ...
...                     ...                   ...                ...  ...
6113                   YUMA               99906.0                  R  ...
6114                   YUMA               49740.0                  U  ...
6115                   YUMA               49740.0                  U  ...
6116  E. BATON ROUGE PARISH               12940.0                  U  ...
6117          SAN FRANCISCO               41884.0                  U  ...

     Net Income from Service to Patients  Total Other Income  Total Income  \
0                              3885386.0            282333.0     4167719.0
1                             -6000221.0           5205543.0     -794678.0
2                             -1897650.0           3694407.0     1796757.0
3                           -179388418.0         229952218.0    50563800.0
4                             -7140506.0          10527317.0     3386811.0
...                                  ...                 ...           ...
6113                           -957720.0           1618853.0      661133.0
6114                           5718850.0          20614885.0    26333735.0
6115                           6975502.0            -24724.0     6950778.0
6116                           1497891.0               813.0     1498704.0
6117                        -291236625.0         216982408.0   -74254217.0

     Total Other Expenses  Net Income  Cost To Charge Ratio  \
0                     3.0   4167716.0                   NaN
1                  2754.0   -797432.0              0.525693
2                     NaN   1796757.0              0.308672
3                     NaN  50563800.0              0.268633
4                     NaN   3386811.0              0.100260
...                   ...         ...                   ...
6113             895300.0   -234167.0              0.632121
6114                  NaN  26333735.0              0.207615
6115                  NaN   6950778.0                   NaN
6116                  NaN   1498704.0                   NaN
6117                  NaN -74254217.0              0.286955

      Net Revenue from Medicaid  Medicaid Charges  \
0                           NaN               NaN
1                      234123.0      7.476990e+05
2                    15429157.0      4.882032e+07
3                    20419284.0      9.645565e+07
4                     7349497.0      9.805427e+07
...                         ...               ...
6113                  1474583.0      4.257378e+06
6114                 77284918.0      5.216138e+08
6115                        NaN               NaN
6116                        NaN               NaN
6117                363066030.0      1.616289e+09

      Net Revenue from Stand-Alone SCHIP  Stand-Alone SCHIP Charges
0                                    NaN                        NaN
1                                    NaN                        NaN
2                                    NaN                        NaN
3                                    NaN                        NaN
4                                57736.0                  1496447.0
...                                  ...                        ...
6113                              9078.0                    58303.0
6114                                 NaN                        NaN
6115                                 NaN                        NaN
6116                                 NaN                        NaN
6117                                 NaN                        NaN

[6118 rows x 126 columns]>

In [11]:
df.shape
df.columns

Index(['rpt_rec_num', 'Provider CCN', 'Hospital Name', 'Street Address',
       'City', 'State Code', 'Zip Code', 'County', 'Medicare CBSA Number',
       'Rural Versus Urban',
       ...
       'Net Income from Service to Patients', 'Total Other Income',
       'Total Income', 'Total Other Expenses', 'Net Income',
       'Cost To Charge Ratio', 'Net Revenue from Medicaid', 'Medicaid Charges',
       'Net Revenue from Stand-Alone SCHIP', 'Stand-Alone SCHIP Charges'],
      dtype='object', length=126)

 Calculate measures of central tendency

In [12]:
df['rpt_rec_num'].nunique()

6118

Looking for missingness

In [13]:
df.sample(10)
df.isnull()

percentmissing = pd.DataFrame(df.isnull().sum()).reset_index()
print(percentmissing)

percentmissing.rename(columns = {'index':'variable', 0:'count_missing'})

                                  index     0
0                           rpt_rec_num     0
1                          Provider CCN     0
2                         Hospital Name     0
3                        Street Address     4
4                                  City     0
..                                  ...   ...
121                Cost To Charge Ratio  1427
122           Net Revenue from Medicaid  1602
123                    Medicaid Charges  1610
124  Net Revenue from Stand-Alone SCHIP  5129
125           Stand-Alone SCHIP Charges  5114

[126 rows x 2 columns]

                               variable  count_missing
0                           rpt_rec_num              0
1                          Provider CCN              0
2                         Hospital Name              0
3                        Street Address              4
4                                  City              0
..                                  ...            ...
121                Cost To Charge Ratio           1427
122           Net Revenue from Medicaid           1602
123                    Medicaid Charges           1610
124  Net Revenue from Stand-Alone SCHIP           5129
125           Stand-Alone SCHIP Charges           5114

[126 rows x 2 columns]

In [14]:
df ['Hospital Name'].value_counts()

ENCOMPASS HEALTH REHABILITATION HOSP    98
GOOD SAMARITAN HOSPITAL                  9
MEMORIAL HOSPITAL                        8
MERCY MEDICAL CENTER                     7
COMMUNITY MEMORIAL HOSPITAL              7
                                        ..
HENRY COUNTY HOSPITAL (CAH)              1
HENRY COUNTY HEALTH CENTER               1
HENRICO DOCTORS HOSPITAL                 1
HENNEPIN COUNTY MEDICAL CENTER           1
ZUCKERBERG SAN FRANCISCO GENERAL         1
Name: Hospital Name, Length: 5728, dtype: int64

In [15]:
df.describe()

,rpt_rec_num,Provider CCN,Medicare CBSA Number,Provider Type,Type of Control,FTE - Employees on Payroll,Number of Interns and Residents (FTE),Total Days Title V,Total Days Title XVIII,Total Days Title XIX,...,Net Income from Service to Patients,Total Other Income,Total Income,Total Other Expenses,Net Income,Cost To Charge Ratio,Net Revenue from Medicaid,Medicaid Charges,Net Revenue from Stand-Alone SCHIP,Stand-Alone SCHIP Charges
count,6118.000000,6118.000000,6049.000000,6118.000000,6118.000000,6013.000000,1399.000000,189.000000,5989.000000,5148.000000,...,6.026000e+03,5.799000e+03,6.013000e+03,1.846000e+03,6.013000e+03,4691.000000,4.516000e+03,4.508000e+03,9.890000e+02,1.004000e+03
mean,701947.693200,269300.869729,53319.985122,2.045767,4.196143,847.636464,92.601751,1888.047619,8676.068292,3527.285159,...,-7.969686e+06,2.037738e+07,1.166524e+07,4.560821e+06,1.026506e+07,1.031930,2.419027e+07,1.464233e+08,7.456442e+05,4.376319e+06
std,14244.457371,158309.214824,34148.787334,1.416823,3.200218,1600.220777,161.036721,3692.237397,13250.364850,8147.232107,...,8.332967e+07,7.780671e+07,7.139321e+07,3.178207e+07,7.186361e+07,33.677305,5.671014e+07,3.157762e+08,2.794916e+06,1.803438e+07
min,649071.000000,10001.000000,10180.000000,1.000000,1.000000,0.050000,0.010000,1.000000,1.000000,1.000000,...,-1.216407e+09,-7.710121e+08,-9.800109e+08,-4.310310e+08,-9.800109e+08,0.055417,-1.824483e+06,2.000000e+00,3.400000e+01,9.000000e+01
25%,694474.250000,140185.250000,26420.000000,1.000000,2.000000,127.880000,8.510000,61.000000,1245.000000,122.000000,...,-7.091676e+06,5.647925e+05,-7.511960e+05,1.000000e+00,-9.019650e+05,0.199217,1.930778e+06,8.024058e+06,2.511200e+04,1.226270e+05
50%,706893.000000,260061.500000,39380.000000,2.000000,3.000000,293.750000,26.660000,514.000000,3436.000000,754.000000,...,-1.062568e+06,2.821260e+06,1.895337e+06,6.592100e+04,1.577785e+06,0.290734,7.086967e+06,3.861739e+07,8.313800e+04,5.500755e+05
75%,711107.750000,392036.750000,99916.000000,2.000000,5.000000,905.020000,98.845000,2323.000000,10564.000000,3379.750000,...,3.450148e+06,1.179821e+07,1.149077e+07,1.531138e+06,1.035629e+07,0.473881,2.200277e+07,1.463105e+08,3.260020e+05,2.281775e+06
max,720507.000000,673071.000000,99966.000000,5.000000,13.000000,27421.420000,1615.330000,32091.000000,193048.000000,178050.000000,...,2.209102e+09,1.740090e+09,2.209102e+09,4.868735e+08,2.209102e+09,2280.353040,1.202144e+09,5.157195e+09,4.307011e+07,3.284642e+08

## Converting variables

In [16]:
df['rpt_rec_num'] = df ['rpt_rec_num'].astype(str)
df.describe()

,Provider CCN,Medicare CBSA Number,Provider Type,Type of Control,FTE - Employees on Payroll,Number of Interns and Residents (FTE),Total Days Title V,Total Days Title XVIII,Total Days Title XIX,Total Days (V + XVIII + XIX + Unknown),...,Net Income from Service to Patients,Total Other Income,Total Income,Total Other Expenses,Net Income,Cost To Charge Ratio,Net Revenue from Medicaid,Medicaid Charges,Net Revenue from Stand-Alone SCHIP,Stand-Alone SCHIP Charges
count,6118.000000,6049.000000,6118.000000,6118.000000,6013.000000,1399.000000,189.000000,5989.000000,5148.000000,6036.000000,...,6.026000e+03,5.799000e+03,6.013000e+03,1.846000e+03,6.013000e+03,4691.000000,4.516000e+03,4.508000e+03,9.890000e+02,1.004000e+03
mean,269300.869729,53319.985122,2.045767,4.196143,847.636464,92.601751,1888.047619,8676.068292,3527.285159,29905.934228,...,-7.969686e+06,2.037738e+07,1.166524e+07,4.560821e+06,1.026506e+07,1.031930,2.419027e+07,1.464233e+08,7.456442e+05,4.376319e+06
std,158309.214824,34148.787334,1.416823,3.200218,1600.220777,161.036721,3692.237397,13250.364850,8147.232107,47642.780242,...,8.332967e+07,7.780671e+07,7.139321e+07,3.178207e+07,7.186361e+07,33.677305,5.671014e+07,3.157762e+08,2.794916e+06,1.803438e+07
min,10001.000000,10180.000000,1.000000,1.000000,0.050000,0.010000,1.000000,1.000000,1.000000,1.000000,...,-1.216407e+09,-7.710121e+08,-9.800109e+08,-4.310310e+08,-9.800109e+08,0.055417,-1.824483e+06,2.000000e+00,3.400000e+01,9.000000e+01
25%,140185.250000,26420.000000,1.000000,2.000000,127.880000,8.510000,61.000000,1245.000000,122.000000,3298.750000,...,-7.091676e+06,5.647925e+05,-7.511960e+05,1.000000e+00,-9.019650e+05,0.199217,1.930778e+06,8.024058e+06,2.511200e+04,1.226270e+05
50%,260061.500000,39380.000000,2.000000,3.000000,293.750000,26.660000,514.000000,3436.000000,754.000000,11826.500000,...,-1.062568e+06,2.821260e+06,1.895337e+06,6.592100e+04,1.577785e+06,0.290734,7.086967e+06,3.861739e+07,8.313800e+04,5.500755e+05
75%,392036.750000,99916.000000,2.000000,5.000000,905.020000,98.845000,2323.000000,10564.000000,3379.750000,36544.000000,...,3.450148e+06,1.179821e+07,1.149077e+07,1.531138e+06,1.035629e+07,0.473881,2.200277e+07,1.463105e+08,3.260020e+05,2.281775e+06
max,673071.000000,99966.000000,5.000000,13.000000,27421.420000,1615.330000,32091.000000,193048.000000,178050.000000,721704.000000,...,2.209102e+09,1.740090e+09,2.209102e+09,4.868735e+08,2.209102e+09,2280.353040,1.202144e+09,5.157195e+09,4.307011e+07,3.284642e+08

In [17]:
df['Provider CCN'] = df ['Provider CCN'].astype(str)
df.describe()

,Medicare CBSA Number,Provider Type,Type of Control,FTE - Employees on Payroll,Number of Interns and Residents (FTE),Total Days Title V,Total Days Title XVIII,Total Days Title XIX,Total Days (V + XVIII + XIX + Unknown),Number of Beds,...,Net Income from Service to Patients,Total Other Income,Total Income,Total Other Expenses,Net Income,Cost To Charge Ratio,Net Revenue from Medicaid,Medicaid Charges,Net Revenue from Stand-Alone SCHIP,Stand-Alone SCHIP Charges
count,6049.000000,6118.000000,6118.000000,6013.000000,1399.000000,189.000000,5989.000000,5148.000000,6036.000000,6045.000000,...,6.026000e+03,5.799000e+03,6.013000e+03,1.846000e+03,6.013000e+03,4691.000000,4.516000e+03,4.508000e+03,9.890000e+02,1.004000e+03
mean,53319.985122,2.045767,4.196143,847.636464,92.601751,1888.047619,8676.068292,3527.285159,29905.934228,146.508189,...,-7.969686e+06,2.037738e+07,1.166524e+07,4.560821e+06,1.026506e+07,1.031930,2.419027e+07,1.464233e+08,7.456442e+05,4.376319e+06
std,34148.787334,1.416823,3.200218,1600.220777,161.036721,3692.237397,13250.364850,8147.232107,47642.780242,789.562299,...,8.332967e+07,7.780671e+07,7.139321e+07,3.178207e+07,7.186361e+07,33.677305,5.671014e+07,3.157762e+08,2.794916e+06,1.803438e+07
min,10180.000000,1.000000,1.000000,0.050000,0.010000,1.000000,1.000000,1.000000,1.000000,1.000000,...,-1.216407e+09,-7.710121e+08,-9.800109e+08,-4.310310e+08,-9.800109e+08,0.055417,-1.824483e+06,2.000000e+00,3.400000e+01,9.000000e+01
25%,26420.000000,1.000000,2.000000,127.880000,8.510000,61.000000,1245.000000,122.000000,3298.750000,25.000000,...,-7.091676e+06,5.647925e+05,-7.511960e+05,1.000000e+00,-9.019650e+05,0.199217,1.930778e+06,8.024058e+06,2.511200e+04,1.226270e+05
50%,39380.000000,2.000000,3.000000,293.750000,26.660000,514.000000,3436.000000,754.000000,11826.500000,66.000000,...,-1.062568e+06,2.821260e+06,1.895337e+06,6.592100e+04,1.577785e+06,0.290734,7.086967e+06,3.861739e+07,8.313800e+04,5.500755e+05
75%,99916.000000,2.000000,5.000000,905.020000,98.845000,2323.000000,10564.000000,3379.750000,36544.000000,171.000000,...,3.450148e+06,1.179821e+07,1.149077e+07,1.531138e+06,1.035629e+07,0.473881,2.200277e+07,1.463105e+08,3.260020e+05,2.281775e+06
max,99966.000000,5.000000,13.000000,27421.420000,1615.330000,32091.000000,193048.000000,178050.000000,721704.000000,52913.000000,...,2.209102e+09,1.740090e+09,2.209102e+09,4.868735e+08,2.209102e+09,2280.353040,1.202144e+09,5.157195e+09,4.307011e+07,3.284642e+08

In [18]:
df['Medicare CBSA Number'] = df ['Medicare CBSA Number'].astype(str)
df.describe()

,Provider Type,Type of Control,FTE - Employees on Payroll,Number of Interns and Residents (FTE),Total Days Title V,Total Days Title XVIII,Total Days Title XIX,Total Days (V + XVIII + XIX + Unknown),Number of Beds,Total Bed Days Available,...,Net Income from Service to Patients,Total Other Income,Total Income,Total Other Expenses,Net Income,Cost To Charge Ratio,Net Revenue from Medicaid,Medicaid Charges,Net Revenue from Stand-Alone SCHIP,Stand-Alone SCHIP Charges
count,6118.000000,6118.000000,6013.000000,1399.000000,189.000000,5989.000000,5148.000000,6036.000000,6045.000000,6045.000000,...,6.026000e+03,5.799000e+03,6.013000e+03,1.846000e+03,6.013000e+03,4691.000000,4.516000e+03,4.508000e+03,9.890000e+02,1.004000e+03
mean,2.045767,4.196143,847.636464,92.601751,1888.047619,8676.068292,3527.285159,29905.934228,146.508189,47639.244169,...,-7.969686e+06,2.037738e+07,1.166524e+07,4.560821e+06,1.026506e+07,1.031930,2.419027e+07,1.464233e+08,7.456442e+05,4.376319e+06
std,1.416823,3.200218,1600.220777,161.036721,3692.237397,13250.364850,8147.232107,47642.780242,789.562299,63079.140658,...,8.332967e+07,7.780671e+07,7.139321e+07,3.178207e+07,7.186361e+07,33.677305,5.671014e+07,3.157762e+08,2.794916e+06,1.803438e+07
min,1.000000,1.000000,0.050000,0.010000,1.000000,1.000000,1.000000,1.000000,1.000000,190.000000,...,-1.216407e+09,-7.710121e+08,-9.800109e+08,-4.310310e+08,-9.800109e+08,0.055417,-1.824483e+06,2.000000e+00,3.400000e+01,9.000000e+01
25%,1.000000,2.000000,127.880000,8.510000,61.000000,1245.000000,122.000000,3298.750000,25.000000,9150.000000,...,-7.091676e+06,5.647925e+05,-7.511960e+05,1.000000e+00,-9.019650e+05,0.199217,1.930778e+06,8.024058e+06,2.511200e+04,1.226270e+05
50%,2.000000,3.000000,293.750000,26.660000,514.000000,3436.000000,754.000000,11826.500000,66.000000,22692.000000,...,-1.062568e+06,2.821260e+06,1.895337e+06,6.592100e+04,1.577785e+06,0.290734,7.086967e+06,3.861739e+07,8.313800e+04,5.500755e+05
75%,2.000000,5.000000,905.020000,98.845000,2323.000000,10564.000000,3379.750000,36544.000000,171.000000,61488.000000,...,3.450148e+06,1.179821e+07,1.149077e+07,1.531138e+06,1.035629e+07,0.473881,2.200277e+07,1.463105e+08,3.260020e+05,2.281775e+06
max,5.000000,13.000000,27421.420000,1615.330000,32091.000000,193048.000000,178050.000000,721704.000000,52913.000000,998275.000000,...,2.209102e+09,1.740090e+09,2.209102e+09,4.868735e+08,2.209102e+09,2280.353040,1.202144e+09,5.157195e+09,4.307011e+07,3.284642e+08

In [ ]:
df['Provider Type'] = df ['Provider Type'].astype(str)
df.describe()

In [28]:
df['Type of Control'] = df ['Type of Control'].astype(str)
df.describe()

,Provider Type,FTE - Employees on Payroll,Number of Interns and Residents (FTE),Total Days Title V,Total Days Title XVIII,Total Days Title XIX,Total Days (V + XVIII + XIX + Unknown),Number of Beds,Total Bed Days Available,Total Discharges Title V,...,Net Income from Service to Patients,Total Other Income,Total Income,Total Other Expenses,Net Income,Cost To Charge Ratio,Net Revenue from Medicaid,Medicaid Charges,Net Revenue from Stand-Alone SCHIP,Stand-Alone SCHIP Charges
count,6118.000000,6013.000000,1399.000000,189.000000,5989.000000,5148.000000,6036.000000,6045.000000,6045.000000,179.000000,...,6.026000e+03,5.799000e+03,6.013000e+03,1.846000e+03,6.013000e+03,4691.000000,4.516000e+03,4.508000e+03,9.890000e+02,1.004000e+03
mean,2.045767,847.636464,92.601751,1888.047619,8676.068292,3527.285159,29905.934228,146.508189,47639.244169,406.972067,...,-7.969686e+06,2.037738e+07,1.166524e+07,4.560821e+06,1.026506e+07,1.031930,2.419027e+07,1.464233e+08,7.456442e+05,4.376319e+06
std,1.416823,1600.220777,161.036721,3692.237397,13250.364850,8147.232107,47642.780242,789.562299,63079.140658,589.272094,...,8.332967e+07,7.780671e+07,7.139321e+07,3.178207e+07,7.186361e+07,33.677305,5.671014e+07,3.157762e+08,2.794916e+06,1.803438e+07
min,1.000000,0.050000,0.010000,1.000000,1.000000,1.000000,1.000000,1.000000,190.000000,1.000000,...,-1.216407e+09,-7.710121e+08,-9.800109e+08,-4.310310e+08,-9.800109e+08,0.055417,-1.824483e+06,2.000000e+00,3.400000e+01,9.000000e+01
25%,1.000000,127.880000,8.510000,61.000000,1245.000000,122.000000,3298.750000,25.000000,9150.000000,10.500000,...,-7.091676e+06,5.647925e+05,-7.511960e+05,1.000000e+00,-9.019650e+05,0.199217,1.930778e+06,8.024058e+06,2.511200e+04,1.226270e+05
50%,2.000000,293.750000,26.660000,514.000000,3436.000000,754.000000,11826.500000,66.000000,22692.000000,146.000000,...,-1.062568e+06,2.821260e+06,1.895337e+06,6.592100e+04,1.577785e+06,0.290734,7.086967e+06,3.861739e+07,8.313800e+04,5.500755e+05
75%,2.000000,905.020000,98.845000,2323.000000,10564.000000,3379.750000,36544.000000,171.000000,61488.000000,569.000000,...,3.450148e+06,1.179821e+07,1.149077e+07,1.531138e+06,1.035629e+07,0.473881,2.200277e+07,1.463105e+08,3.260020e+05,2.281775e+06
max,5.000000,27421.420000,1615.330000,32091.000000,193048.000000,178050.000000,721704.000000,52913.000000,998275.000000,2932.000000,...,2.209102e+09,1.740090e+09,2.209102e+09,4.868735e+08,2.209102e+09,2280.353040,1.202144e+09,5.157195e+09,4.307011e+07,3.284642e+08

In [29]:
c

,Provider Type,FTE - Employees on Payroll,Number of Interns and Residents (FTE),Total Days Title V,Total Days Title XVIII,Total Days Title XIX,Total Days (V + XVIII + XIX + Unknown),Number of Beds,Total Bed Days Available,Total Discharges Title V,...,Net Income from Service to Patients,Total Other Income,Total Income,Total Other Expenses,Net Income,Cost To Charge Ratio,Net Revenue from Medicaid,Medicaid Charges,Net Revenue from Stand-Alone SCHIP,Stand-Alone SCHIP Charges
count,6118.000000,6013.000000,1399.000000,189.000000,5989.000000,5148.000000,6036.000000,6045.000000,6045.000000,179.000000,...,6.026000e+03,5.799000e+03,6.013000e+03,1.846000e+03,6.013000e+03,4691.000000,4.516000e+03,4.508000e+03,9.890000e+02,1.004000e+03
mean,2.045767,847.636464,92.601751,1888.047619,8676.068292,3527.285159,29905.934228,146.508189,47639.244169,406.972067,...,-7.969686e+06,2.037738e+07,1.166524e+07,4.560821e+06,1.026506e+07,1.031930,2.419027e+07,1.464233e+08,7.456442e+05,4.376319e+06
std,1.416823,1600.220777,161.036721,3692.237397,13250.364850,8147.232107,47642.780242,789.562299,63079.140658,589.272094,...,8.332967e+07,7.780671e+07,7.139321e+07,3.178207e+07,7.186361e+07,33.677305,5.671014e+07,3.157762e+08,2.794916e+06,1.803438e+07
min,1.000000,0.050000,0.010000,1.000000,1.000000,1.000000,1.000000,1.000000,190.000000,1.000000,...,-1.216407e+09,-7.710121e+08,-9.800109e+08,-4.310310e+08,-9.800109e+08,0.055417,-1.824483e+06,2.000000e+00,3.400000e+01,9.000000e+01
25%,1.000000,127.880000,8.510000,61.000000,1245.000000,122.000000,3298.750000,25.000000,9150.000000,10.500000,...,-7.091676e+06,5.647925e+05,-7.511960e+05,1.000000e+00,-9.019650e+05,0.199217,1.930778e+06,8.024058e+06,2.511200e+04,1.226270e+05
50%,2.000000,293.750000,26.660000,514.000000,3436.000000,754.000000,11826.500000,66.000000,22692.000000,146.000000,...,-1.062568e+06,2.821260e+06,1.895337e+06,6.592100e+04,1.577785e+06,0.290734,7.086967e+06,3.861739e+07,8.313800e+04,5.500755e+05
75%,2.000000,905.020000,98.845000,2323.000000,10564.000000,3379.750000,36544.000000,171.000000,61488.000000,569.000000,...,3.450148e+06,1.179821e+07,1.149077e+07,1.531138e+06,1.035629e+07,0.473881,2.200277e+07,1.463105e+08,3.260020e+05,2.281775e+06
max,5.000000,27421.420000,1615.330000,32091.000000,193048.000000,178050.000000,721704.000000,52913.000000,998275.000000,2932.000000,...,2.209102e+09,1.740090e+09,2.209102e+09,4.868735e+08,2.209102e+09,2280.353040,1.202144e+09,5.157195e+09,4.307011e+07,3.284642e+08

In [30]:
df['Fiscal Year End Date'] = df ['Fiscal Year End Date'].astype(str)
df.describe()

,Provider Type,FTE - Employees on Payroll,Number of Interns and Residents (FTE),Total Days Title V,Total Days Title XVIII,Total Days Title XIX,Total Days (V + XVIII + XIX + Unknown),Number of Beds,Total Bed Days Available,Total Discharges Title V,...,Net Income from Service to Patients,Total Other Income,Total Income,Total Other Expenses,Net Income,Cost To Charge Ratio,Net Revenue from Medicaid,Medicaid Charges,Net Revenue from Stand-Alone SCHIP,Stand-Alone SCHIP Charges
count,6118.000000,6013.000000,1399.000000,189.000000,5989.000000,5148.000000,6036.000000,6045.000000,6045.000000,179.000000,...,6.026000e+03,5.799000e+03,6.013000e+03,1.846000e+03,6.013000e+03,4691.000000,4.516000e+03,4.508000e+03,9.890000e+02,1.004000e+03
mean,2.045767,847.636464,92.601751,1888.047619,8676.068292,3527.285159,29905.934228,146.508189,47639.244169,406.972067,...,-7.969686e+06,2.037738e+07,1.166524e+07,4.560821e+06,1.026506e+07,1.031930,2.419027e+07,1.464233e+08,7.456442e+05,4.376319e+06
std,1.416823,1600.220777,161.036721,3692.237397,13250.364850,8147.232107,47642.780242,789.562299,63079.140658,589.272094,...,8.332967e+07,7.780671e+07,7.139321e+07,3.178207e+07,7.186361e+07,33.677305,5.671014e+07,3.157762e+08,2.794916e+06,1.803438e+07
min,1.000000,0.050000,0.010000,1.000000,1.000000,1.000000,1.000000,1.000000,190.000000,1.000000,...,-1.216407e+09,-7.710121e+08,-9.800109e+08,-4.310310e+08,-9.800109e+08,0.055417,-1.824483e+06,2.000000e+00,3.400000e+01,9.000000e+01
25%,1.000000,127.880000,8.510000,61.000000,1245.000000,122.000000,3298.750000,25.000000,9150.000000,10.500000,...,-7.091676e+06,5.647925e+05,-7.511960e+05,1.000000e+00,-9.019650e+05,0.199217,1.930778e+06,8.024058e+06,2.511200e+04,1.226270e+05
50%,2.000000,293.750000,26.660000,514.000000,3436.000000,754.000000,11826.500000,66.000000,22692.000000,146.000000,...,-1.062568e+06,2.821260e+06,1.895337e+06,6.592100e+04,1.577785e+06,0.290734,7.086967e+06,3.861739e+07,8.313800e+04,5.500755e+05
75%,2.000000,905.020000,98.845000,2323.000000,10564.000000,3379.750000,36544.000000,171.000000,61488.000000,569.000000,...,3.450148e+06,1.179821e+07,1.149077e+07,1.531138e+06,1.035629e+07,0.473881,2.200277e+07,1.463105e+08,3.260020e+05,2.281775e+06
max,5.000000,27421.420000,1615.330000,32091.000000,193048.000000,178050.000000,721704.000000,52913.000000,998275.000000,2932.000000,...,2.209102e+09,1.740090e+09,2.209102e+09,4.868735e+08,2.209102e+09,2280.353040,1.202144e+09,5.157195e+09,4.307011e+07,3.284642e+08